apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sandyxd18/frontend-tubes:v1
        ports:
        - containerPort: 80
        env:
          - name: VITE_BASE_URL
            valueFrom:
              secretKeyRef:
                name: frontend-secret
                key: VITE_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80