apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    # app: frontend
    name: frontend-service
  ports:
    - port: 80
      targetPort: 80